apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: default
data:
  RABBITMQ_DEFAULT_USER: default_user
  RABBITMQ_DEFAULT_PASS: default_pass
  RABBITMQ_DEFAULT_VHOST: default_vhost
