name: Deploy Formatio API

on:
  repository_dispatch:
    types:
      - api.formatio

jobs:
  deploy:
    if: ${{ github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.client_payload.tag_name }}

    steps:
      - run: echo "Deploying ${{ env.TAG_NAME }}"

      - name: Checkout master
        uses: actions/checkout@main

      - name: Update Deployment file
        run: |
          sed -E 's|image: ghcr\.io/overal-x/api\.formatio:[a-zA-Z0-9.-]+|image: ghcr.io/overal-x/api.formatio:${{ env.TAG_NAME }}|g' \
          k8s/formatio/formatio.yaml > k8s/formatio/formatio-mod.yaml
          mv k8s/formatio/formatio-mod.yaml k8s/formatio/formatio.yaml
 
      - name: Commit changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: k8s/api/formatio.yaml
          commit-msg: deploy formatio api ${{ env.TAG_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
