name: Deploy Formatio API

on:
  repository_dispatch:
    types:
      - api.formatio

jobs:
  deploy:
    if: ${{ github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.client_payload.tag_name }}

    steps:
      - run: echo "Deploying ${{ env.TAG_NAME }}"

      - name: Checkout master
        uses: actions/checkout@main
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Update Deployment file
        run: |
          sed 's|image: ghcr.io/overal-x/api.formatio:development|image: ghcr.io/overal-x/api.formatio:${{ env.TAG_NAME }}|g' \
          k8s/formatio.yaml > k8s/modified-formatio.yaml
          mv k8s/modified-formatio.yaml k8s/formatio.yaml

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/k8s/formatio.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/formatio-api-deployment
