name: Deploy Formatio API

on:
  repository_dispatch:
    types:
      - api.formatio

jobs:
  deploy:
    if: ${{ github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
